GET http://localhost:4000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsIm5hbWUiOiJhZGEiLCJlbWFpbCI6ImFAMS5jb20iLCJpYXQiOjE2ODc1MzA0NDgsImV4cCI6MTY4NzUzMDQ2OH0.1GHJBXrXahVB_scQaOc6KIkNpFlNxz9t32K2_0CuoSc

###
GET http://localhost:4000/karyawan
###

GET http://localhost:4000/users/1

###

POST http://localhost:4000/register
Content-Type: application/json

{
    "name" : "ada",
    "email" : "a@1.com", 
    "password" : "123",
    "confPassword" : "123"
}

###

PATCH  http://localhost:4000/users/9
Content-Type: application/json

{
    "name" : "add",
    "email" : "a@a.com", 
    "password" : "123",
    "confPassword" : "123"
}
###

POST http://localhost:4000/login
Content-Type: application/json

{
    
    "email" : "a@1.com", 
    "password" : "123"
    
   
}

###
GET http://localhost:4000/token

###
DELETE http://localhost:4000/users/

###
DELETE http://localhost:4000/logout